idf_component_register(
    SRCS
        "minicore_app.c"
        "minicore_usb.c"
        "minicore_bridge.c"
        "waveshare_s3_lcd147_ui.c"
    INCLUDE_DIRS
        "."
        "${CMAKE_CURRENT_SOURCE_DIR}/../../common"
    REQUIRES
        nvs_flash
        esp_wifi
        esp_netif
        esp_event
        esp_driver_spi
        esp_driver_gpio
        esp_driver_ledc
        esp_lcd
        esp_timer
        espressif__esp_tinyusb
        driver
        freertos
        esp_hw_support
        esp_system
        led_strip
        esp_lvgl_port
        lvgl
)
