# Sanity Check for Robot
name: Firmware Robot

on:
  pull_request:
    branches:
      - main
    paths:
      - 'firmware/esp32-robot/**/*.py'
      - '.github/workflows/pyright.yml'

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install pyright
        run: pip install pyright

      - name: Run pyright
        working-directory: firmware/esp32-robot
        run: pyright .
